src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 200)]
    #[Assert\Length(min:3)]
    private $titre;

    #[ORM\Column(type: 'text')]
    #[Assert\Length(min:3)]
    private $contenu;

    #[ORM\Column(type: 'datetime')]
    #[Assert\Type("datetime")]
    private $dt_creation;

    #[ORM\ManyToOne(targetEntity:User::class, inversedBy:"articles", cascade:["persist", "remove"])]
    private $user;

    public function __construct()
    {
        $tz = new \DateTimeZone('Europe/Paris');
        $now = new \DateTime();
        $now->setTimezone($tz);	
        $this->setDtCreation($now);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDtCreation(): ?\DateTimeInterface
    {
        return $this->dt_creation;
    }

    public function setDtCreation(\DateTimeInterface $dt_creation): self
    {
        $this->dt_creation = $dt_creation;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

templates/commun/list-articles.html.twig
        <article>
            <h2>{{ article.titre }}</h2>
            <p>{{ article.contenu }}</p>
            <ul>
                <li>{{ article.dtCreation | date("d/m/Y") }}</li>   
                <li>{{ article.user ? article.user.email : "auteur inconnu" }}</li>
            </ul>
        </article>
        <hr>

templates/commun/menu.html.twig
        {# {{ dump(app.user) }} #}
        <ul class="list-inline">
            <li class="list-inline-item"><a href="{{ path("home_index")}}">Accueil</a></li>
            {% if is_granted("ROLE_REDACTEUR") %}
                <li class="list-inline-item"><a href="{{ path("home_article")}}">Article</a></li>
                {# <li class="list-inline-item"><a href="{{ path("search_result")}}">Resultat</a></li> #}
            {% endif %}
            {% if is_granted("ROLE_ADMIN") %}
                <li class="list-inline-item"><a href="{{ path("home_new_article")}}">Créer un article</a></li>
                <li class="list-inline-item"><a href="{{ path("home_edit")}}">Edit</a></li>
                <li class="list-inline-item"><a href="{{ path("app_register")}}">Inscription</a></li> 
            {% endif %}
            {% if app.user is null %}
                <li class="list-inline-item"><a href="{{ path("app_login")}}">Connexion</a></li>
            {% else %}
                <li class="list-inline-item"><a href="{{ path("app_logout")}}">Déconnexion</a></li>
            {% endif %}
        </ul>